import type { Request, Response } from 'express';
export default function handler(request: Request<unknown, unknown, {
    shiftId: number | string;
    adhocTaskTypeDataListItemId: number | string;
    taskDescription: string;
    locationAddress1: string;
    locationAddress2: string;
    locationCityProvince: string;
    locationLatitude: number | string | null | undefined;
    locationLongitude: number | string | null | undefined;
    fromLocationAddress1: string;
    fromLocationAddress2: string;
    fromLocationCityProvince: string;
    fromLocationLatitude: number | string | null | undefined;
    fromLocationLongitude: number | string | null | undefined;
    toLocationAddress1: string;
    toLocationAddress2: string;
    toLocationCityProvince: string;
    toLocationLatitude: number | string | null | undefined;
    toLocationLongitude: number | string | null | undefined;
    taskDueDateTimeString: string | null | undefined;
    shiftAdhocTaskNote: string;
}>, response: Response): Promise<void>;
