import type { Request, Response } from 'express';
type LatitudeLongitude = number | string | null | undefined;
export type DoUpdateAdhocTaskResponse = {
    success: boolean;
    errorMessage?: string;
    shiftAdhocTasks?: ShiftAdhocTask[];
};
export default function handler(request: Request<unknown, unknown, {
    adhocTaskId: number | string;
    adhocTaskTypeDataListItemId: number | string;
    taskDescription: string;
    shiftId: number | string;
    locationAddress1: string;
    locationAddress2: string;
    locationCityProvince: string;
    locationLatitude: LatitudeLongitude;
    locationLongitude: LatitudeLongitude;
    fromLocationAddress1: string;
    fromLocationAddress2: string;
    fromLocationCityProvince: string;
    fromLocationLatitude: LatitudeLongitude;
    fromLocationLongitude: LatitudeLongitude;
    toLocationAddress1: string;
    toLocationAddress2: string;
    toLocationCityProvince: string;
    toLocationLatitude: LatitudeLongitude;
    toLocationLongitude: LatitudeLongitude;
    taskCompleteDateTimeString: string | null | undefined;
    taskDueDateTimeString: string | null | undefined;
}>, response: Response<DoUpdateAdhocTaskResponse>): Promise<void>;
export {};
