import type { ActiveDirectoryAuthenticatorConfiguration, ADWebAuthAuthenticatorConfiguration, FunctionAuthenticatorConfiguration, PlainTextAuthenticatorConfiguration } from '@cityssm/authentication-helper';
import type { AvantiApiConfiguration } from '@cityssm/avanti-api';
import type { config as MSSQLConfig } from 'mssql';
import type { NotificationType } from '../tasks/notifications/types.js';
import type { ConfigEmail, ConfigEmployees, ConfigEquipment, ConfigLocations } from '../types/config.types.js';
export declare const configDefaultValues: {
    'application.applicationName': string;
    'application.applicationUrl': string | undefined;
    'application.backgroundImage': string;
    'application.instance': string;
    'application.httpPort': number;
    'application.maximumProcesses': number;
    'application.attachmentMaximumFileSizeBytes': number;
    'application.attachmentStoragePath': string;
    'login.authentication': {
        config: ActiveDirectoryAuthenticatorConfiguration;
        type: "activeDirectory";
    } | {
        config: ADWebAuthAuthenticatorConfiguration;
        type: "adWebAuth";
    } | {
        config: FunctionAuthenticatorConfiguration;
        type: "function";
    } | {
        config: PlainTextAuthenticatorConfiguration;
        type: "plainText";
    } | undefined;
    'login.domain': string;
    'reverseProxy.disableCompression': boolean;
    'reverseProxy.disableCsrf': boolean;
    'reverseProxy.disableEtag': boolean;
    'reverseProxy.disableRateLimit': boolean;
    'reverseProxy.trafficIsForwarded': boolean;
    'reverseProxy.urlPrefix': string;
    'session.cookieName': string;
    'session.doKeepAlive': boolean;
    'session.maxAgeMillis': any;
    'session.secret': string;
    'connectors.shiftLog': MSSQLConfig;
    'connectors.avanti': AvantiApiConfiguration | undefined;
    'connectors.ntfy': {
        serverUrl?: string;
        defaultTopic: string;
    } | undefined;
    'connectors.ntfy.serverUrl': any;
    'connectors.pearl': MSSQLConfig | undefined;
    'connectors.email': ConfigEmail | undefined;
    'shifts.isEnabled': boolean;
    'shifts.router': string;
    'shifts.sectionName': string;
    'shifts.sectionNameSingular': string;
    'shifts.iconClass': string;
    'workOrders.isEnabled': boolean;
    'workOrders.router': string;
    'workOrders.sectionName': string;
    'workOrders.sectionNameSingular': string;
    'workOrders.iconClass': string;
    'timesheets.isEnabled': boolean;
    'timesheets.router': string;
    'timesheets.sectionName': string;
    'timesheets.sectionNameSingular': string;
    'timesheets.iconClass': string;
    employees: ConfigEmployees;
    'employees.syncSource': string;
    equipment: ConfigEquipment;
    'equipment.syncSource': string;
    locations: ConfigLocations;
    'locations.syncSource': string;
    'notifications.protocols': NotificationType[];
};
export default configDefaultValues;
