export interface ShiftLogGlobal {
    apiKey: string;
    sessionKeepAliveMillis: number;
    urlPrefix: string;
    defaultLatitude: number;
    defaultLongitude: number;
    shiftsAreEnabled: boolean;
    shiftsRouter: string;
    shiftsSectionName: string;
    shiftsSectionNameSingular: string;
    buildShiftURL: (shiftId: number, edit?: boolean) => string;
    workOrdersAreEnabled: boolean;
    workOrdersRouter: string;
    workOrdersSectionName: string;
    workOrdersSectionNameSingular: string;
    userCanManageWorkOrders: boolean;
    userCanUpdateWorkOrders: boolean;
    buildWorkOrderURL: (workOrderId: number, edit?: boolean) => string;
    timesheetsAreEnabled: boolean;
    timesheetsRouter: string;
    timesheetsSectionName: string;
    timesheetsSectionNameSingular: string;
    buildTimesheetURL: (timesheetId: number, edit?: boolean) => string;
    isAdmin: boolean;
    userName: string;
    clearUnsavedChanges: () => void;
    hasUnsavedChanges: () => boolean;
    setUnsavedChanges: () => void;
    initializeRecordTabs: (tabsContainerElement: HTMLElement) => void;
    buildPaginationControls: (totalCount: number, currentPageOrOffset: number, itemsPerPageOrLimit: number, clickHandler: (pageNumber: number) => void) => HTMLElement;
}
