import type { DateString, TimeString } from '@cityssm/utils-datetime';
export type UpdateWorkOrderForm = Record<`moreInfo_${string}`, unknown> & {
    workOrderId: number | string;
    workOrderDetails: string;
    workOrderStatusDataListItemId?: number | string;
    workOrderPriorityDataListItemId?: number | string;
    workOrderTypeId: number | string;
    workOrderOpenDateTimeString: `${DateString} ${TimeString}` | `${DateString}T${TimeString}`;
    workOrderDueDateTimeString: '' | `${DateString} ${TimeString}` | `${DateString}T${TimeString}`;
    workOrderCloseDateTimeString: '' | `${DateString} ${TimeString}` | `${DateString}T${TimeString}`;
    requestorContactInfo: string;
    requestorName: string;
    locationLatitude?: number | string;
    locationLongitude?: number | string;
    locationAddress1: string;
    locationAddress2: string;
    locationCityProvince: string;
    assignedToDataListItemId?: number | string;
};
export default function updateWorkOrder(updateWorkOrderForm: UpdateWorkOrderForm, userName: string): Promise<boolean>;
